//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTask2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableForWPFapp
    {
        public int idkey { get; set; }
        public string name { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
