//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTask2.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class tableForWPFapp
    {
        public int idkey { get; set; }
        public string name { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
